# To run: docker-compose run
#
# Create a .env file in the same folder as this file and change the variables.
# MOUNT_POINT=/tmp/
# VPN_PROVIDER=changeme
# VPN_CONFIG=changeme
# VPN_USERNAME=changeme
# VPN_PASSWORD=changeme
#
#
version: "2"

services:

  transmission:
    image: haugene/transmission-openvpn
    container_name: transmission-openvpn
    restart: always
    ports:
      - "9091:9091"
    networks:
      - lsdnet
    environment:
      - PGID=100
      - PUID=1000
      - CREATE_TUN_DEVICE=true
      - OPENVPN_PROVIDER=${VPN_PROVIDER}
      - OPENVPN_CONFIG=${VPN_CONFIG}
      - OPENVPN_USERNAME=${VPN_USERNAME}
      - OPENVPN_PASSWORD=${VPN_PASSWORD}
      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
    cap_add:
      - NET_ADMIN
    volumes:
      - ${MOUNT_POINT}/transmission:/data
      - /etc/localtime:/etc/localtime:ro
    dns:
      - 9.9.9.9
      - 149.112.112.112

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    restart: always
    ports:
      - "7878:7878"
    networks:
      - lsdnet
    environment:
      - PGID=100
      - PUID=1000
      - TZ=America/Chicago
    volumes:
      - ${MOUNT_POINT}/radarr/config:/config
      - ${MOUNT_POINT}/transmission/completed:/downloads
      - ${MOUNT_POINT}/plex/movies:/movies
      - /media/movies:/media/movies

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    restart: always
    ports:
      - "8989:8989"
    networks:
      - lsdnet
    environment:
      - PGID=100
      - PUID=1000
      - TZ=America/Chicago
    volumes:
      - ${MOUNT_POINT}/sonarr/config:/config
      - ${MOUNT_POINT}/plex/tv:/tv
      - ${MOUNT_POINT}/transmission/completed:/downloads
      - /media/television:/media/tv

  lidarr:
    image: linuxserver/lidarr
    container_name: lidarr
    restart: always
    ports:
      - "8686:8686"
    networks:
      - lsdnet
    environment:
      - PUID=1000
      - PGID=100
      - TZ=America/Chicago
      - UMASK_SET=022 #optional
    volumes:
      - ${MOUNT_POINT}/lidarr/config:/config
      - ${MOUNT_POINT}/plex/music:/music
      - ${MOUNT_POINT}/transmission/completed:/downloads
      - /media/music:/media/music

  jackett:
    image: linuxserver/jackett
    container_name: jackett
    restart: always
    networks:
      - lsdnet
    environment:
      - PGID=100
      - PUID=1000
      - TZ=America/Chicago
    volumes:
      - ${MOUNT_POINT}/jackett/config:/config
      - ${MOUNT_POINT}/jackett/downloads:/downloads
    ports:
      - "9117:9117"

#  plex:
#    image: timhaak/plex
#    container_name: plex
#    restart: always
#    ports:
#      - "32400:32400"
#      - "1900:1900"
#      - "3005:3005"
#      - "5353:5353"
#      - "8324:8324"
#      - "32410:32410"
#      - "32412:32412"
#      - "32413:32413"
#      - "32414:32414"
#      - "32469:32469"
#     networks:
#       - lsdnet
#     environment:
#       - PGID=100
#       - PUID=1000
#       - TZ=America/Chicago
#     volumes:
#       - ${MOUNT_POINT}/plex-config:/config
#       - ${MOUNT_POINT}/plex:/data

networks:
  lsdnet:
    driver: bridge
